export function gætKategori(navn) {
  const n = navn.toLowerCase()
  if (/oregano|timian|rosmarin|kanel|paprika|gurkemeje|spidskommen|karry|chiliflager|chilipulver|stødt peber|salt\b|stjerneanis|muskatnød|vaniljesukker|bagepulver|natron|laurbær|nelliker|allehånde|cayenne|hvidløgspulver|fennikelfrø|kardamom|sambal|ras el hanout|garam masala|sichuan|tørret|stødt|pulver|urter|krydderi/.test(n)) return 'krydderier'
  if (/frosn|frossen/.test(n)) return 'frys'
  if (/mælk|fløde|smør|æg|ost|yoghurt|skyr|ricotta|cream cheese|crème fraîche|creme fraiche|mascarpone|kefir|kvark|brie|gedeost|hytteost|flødeos|danbo|cheddar|mozzarella|parmesan|feta/.test(n)) return 'køl'
  if (/kylling|oksekød|svinekød|hakket kød|laks|tun\b|rejer|flæsk\b|bacon|skinke|pølse|lever\b|and\b|lam\b|kalv|kotelet|nakkefilet|mørbrønd|bøf|torsk|sild\b|fisk\b/.test(n)) return 'køl'
  if (/løg|gulerod|tomat|broccoli|blomkål|spinat|agurk|peberfrugt|kartoffel|søde kartofler|avocado|squash|svampe|champignon|aubergine|selleri|fennikel|asparges|porrer|purre|spidskål|grønkål|hvidkål|rødkål|ærter\b|majs|ingefær|citron|lime|appelsin|banan|æble|pære|mango|ananas|jordbær|hindbær|blåbær|tranebær|rabarber|koriander|basilikum|persille|dild|mynte|ramsløg|rucola|salat\b/.test(n)) return 'grønt'
  return 'tørvarer'
}

export function gætEmoji(navn) {
  const n = navn.toLowerCase()
  if (/kylling|høne/.test(n)) return '🍗'
  if (/oksekød|hakket kød|bøf|tartar/.test(n)) return '🥩'
  if (/laks|torsk|fisk|tun\b/.test(n)) return '🐟'
  if (/rejer/.test(n)) return '🦐'
  if (/æg/.test(n)) return '🥚'
  if (/mælk|fløde|kefir/.test(n)) return '🥛'
  if (/smør/.test(n)) return '🧈'
  if (/ost|mozz|parmes|feta|cheddar|brie|gedeost|hytteost/.test(n)) return '🧀'
  if (/tomat/.test(n)) return '🍅'
  if (/løg|purløg|porrer|purre/.test(n)) return '🧅'
  if (/hvidløg/.test(n)) return '🧄'
  if (/gulerod/.test(n)) return '🥕'
  if (/kartoffel/.test(n)) return '🥔'
  if (/broccoli|blomkål|kål/.test(n)) return '🥦'
  if (/spinat|salat\b|rucola/.test(n)) return '🥬'
  if (/avocado/.test(n)) return '🥑'
  if (/citron|lime/.test(n)) return '🍋'
  if (/appelsin/.test(n)) return '🍊'
  if (/banan/.test(n)) return '🍌'
  if (/æble/.test(n)) return '🍎'
  if (/jordbær|hindbær|blåbær|bær/.test(n)) return '🍓'
  if (/mango|ananas/.test(n)) return '🍍'
  if (/champignon|svamp/.test(n)) return '🍄'
  if (/agurk|squash/.test(n)) return '🥒'
  if (/peberfrugt/.test(n)) return '🫑'
  if (/pasta|spaghetti|tagliatelle|penne|rigatoni|fusilli|orzo|lasagne/.test(n)) return '🍝'
  if (/ris\b|quinoa|bulgur|couscous/.test(n)) return '🍚'
  if (/mel\b|hvedemel|rugmel/.test(n)) return '🌾'
  if (/sukker|honning|sirup|melis/.test(n)) return '🍬'
  if (/chokolade/.test(n)) return '🍫'
  if (/salt\b/.test(n)) return '🧂'
  if (/chili|peber/.test(n)) return '🌶️'
  if (/kanel/.test(n)) return '🪵'
  if (/persille|basilikum|koriander|dild|mynte|timian|rosmarin|oregano|ingefær/.test(n)) return '🌿'
  if (/olie/.test(n)) return '🫙'
  if (/brød|rugbrød|baguette|bolle/.test(n)) return '🍞'
  if (/bønner|linser|kikærter/.test(n)) return '🫘'
  if (/kokosmælk|kokos/.test(n)) return '🥥'
  if (/vin\b|hvidvin|rødvin/.test(n)) return '🍷'
  return '🥄'
}

export function gætEnhed(navn) {
  const n = navn.toLowerCase()
  if (/salt|peber|karry|gurkemeje|kanel|spidskommen|paprika|bagepulver|natron|chili|oregano|timian|rosmarin|stødt|tørret|pulver|fennikel|kardamom/.test(n)) return 'tsk'
  if (/olie|sojasauce|eddike|sennep|worcestershire|tabasco|fiskesauce|østerssauce/.test(n)) return 'spsk'
  if (/mælk|fløde|kefir|yoghurt|skyr/.test(n)) return 'dl'
  if (/kød|fisk|laks|kylling|oksekød|smør|ost|mel|sukker|havregryn|bacon|skinke|pasta|ris|linser|kikærter/.test(n)) return 'g'
  if (/løg|tomat|gulerod|kartoffel|æble|citron|banan|æg|peberfrugt|agurk|squash/.test(n)) return 'stk'
  return 'stk'
}
