import { createContext, useContext, useState, useCallback } from 'react'

const LANG_KEY = 'simmer_lang'

// ── Translations ──────────────────────────────────────────────────────────────

const T = {
  da: {
    // Nav
    'nav.hjem':     'Hjem',
    'nav.madmatch': 'Mad-match',
    'nav.opret':    'Opret',
    'nav.lager':    'Lager',
    'nav.profil':   'Profil',

    // Relative time
    'tid.ligeNu':   'Lige nu',
    'tid.minSiden': 'min siden',
    'tid.tSiden':   't siden',
    'tid.dagSiden': 'dag siden',
    'tid.dageSiden':'dage siden',
    'tid.timeEnhed':'t',

    // Sværhed
    'sværhed.1': 'Let',
    'sværhed.2': 'Middel',
    'sværhed.3': 'Svær',

    // Hjem
    'hjem.godmorgen':       'Godmorgen',
    'hjem.godFormiddag':    'God formiddag',
    'hjem.godEftermiddag':  'God eftermiddag',
    'hjem.godAftenen':      'God aften',
    'hjem.klar':            'Klar til at lave mad?',
    'hjem.aktivNu':         'Aktive lige nu',
    'hjem.ingenAktive':     'Ingen venner aktive',
    'hjem.søgPlaceholder':  '🔍 Søg opskrifter…',
    'hjem.søgIngen':        'Ingen resultater for',
    'hjem.streakLabel':     'dages streak!',
    'hjem.senesteFeed':     'Seneste retter i dit netværk',
    'hjem.ingenFeed':       'Intet at vise endnu',
    'hjem.ingenFeedSub':    'Tilføj venner og lav mad for at se aktivitet her.',
    'hjem.likerDu':         'likte',
    'hjem.kokkehat':        '🧑‍🍳',

    // Mad-match
    'mm.kunKanLaves': '✓ Kun hvad jeg kan lave nu',
    'mm.titel':       'Mad-match',
    'mm.subtitle':    'Swipe dig til aftensmaden',
    'mm.mitLager':    '🧺 Mit lager',
    'mm.under30':     '⏱ Under 30 min',
    'mm.vegetar':     'Vegetar',
    'mm.kød':         'Kød',
    'mm.fisk':        'Fisk',
    'mm.morgen':      '🌅 Morgen',
    'mm.frokost':     '🥗 Frokost',
    'mm.aftensmad':   '🍽️ Aftensmad',
    'mm.henter':      'Henter opskrifter…',
    'mm.tomTitel':    'Det var dem!',
    'mm.tomGemte':    'Du gemte',
    'mm.tomRet':      'ret',
    'mm.tomRetter':   'retter',
    'mm.tomForfra':   'Start forfra',

    // Opskrift
    'op.henter':          'Henter opskrift…',
    'op.ikkeFundet':      'Opskrift ikke fundet',
    'op.tilbage':         '← Tilbage',
    'op.ingredienser':    'Ingredienser',
    'op.fremgangsmåde':   'Fremgangsmåde',
    'op.mineNoter':       'Mine noter',
    'op.duHarAlt':        'Du har alt ✓',
    'op.mangler':         'mangler',
    'op.tilpasMængde':    'Tilpas mængde',
    'op.pers':            'pers.',
    'op.stk':             'stk',
    'op.nulstilTil':      'Nulstil til',
    'op.fra':             'fra',
    'op.noterPh':         'Skriv dine egne noter, tilpasninger eller tip her…',
    'op.seOriginal':      'Se original opskrift på',
    'op.tilføjIndkøb':    '🛒 Tilføj manglende til indkøbsliste',
    'op.tilføjAlt':       '🛒 Tilføj alle til indkøbsliste',
    'op.tilføjtBekræft':  'tilføjet til din indkøbsliste!',
    'op.startKnap':       '🍳 Start tilberedning',
    'op.chatSpørg':       'Spørg om opskriften',
    'op.chatPh':          'Stil et spørgsmål…',
    'op.chatVelkomst':    'Hej! Jeg kender denne opskrift ud og ind – hvad vil du vide?',
    'op.chatFejl':        'Beklager, der opstod en fejl. Prøv igen.',
    'op.chatOffTopic':    'Jeg er kun ekspert i denne ret! Spørg mig om ingredienser, tilberedningstips, udskiftninger eller serveringsforslag 😊',
    'op.chatLang':        'Svar altid på dansk.',

    // Kok
    'kok.henter':        'Henter opskrift…',
    'kok.ikkeFundet':    'Opskrift ikke fundet',
    'kok.pause':         '⏸ Pause',
    'kok.start':         '▶ Start',
    'kok.nulstil':       '⏹ Nulstil',
    'kok.ingredienser':  'Ingredienser',
    'kok.trin':          'Trin',
    'kok.af':            'af',
    'kok.afslut':        '✓ Afslut',
    'kok.modal.titel':   'Lykkes det?',
    'kok.modal.brugte':  'Du brugte',
    'kok.modal.på':      'på',
    'kok.modal.tagFoto': 'Tag foto',
    'kok.modal.upload':  'Upload foto',
    'kok.modal.del':     'Del med fællesskabet 🌍',
    'kok.modal.citatPh': 'Tilføj en kommentar… (valgfrit)',
    'kok.modal.fortsæt': 'Fortsæt',
    'kok.modal.gemDel':  'Gem & Del',
    'kok.modal.arkiv':   'Gem til arkiv',
    'kok.modal.gemmer':  'Gemmer…',
    'kok.modal.fejl':    'Foto kunne ikke uploades — prøv igen.',
    'kok.færdig.titel':  'Godt klaret! 🎉',
    'kok.færdig.tekst':  'Din kreation er gemt.',
    'kok.færdig.tilbage':'Tilbage til opskriften',

    // Lager
    'lag.titel':      'Lager',
    'lag.tilføj':     '+ Tilføj',
    'lag.tom':        'Dit lager er tomt',
    'lag.tomSub':     'Tilføj råvarer for at se hvilke opskrifter du kan lave.',
    'lag.søgPh':      'Søg eller skriv navn…',
    'lag.mængde':     'Mængde',
    'lag.enhed':      'Enhed',
    'lag.udløber':    'Udløber',
    'lag.slet':       'Slet',
    'lag.gem':        'Gem',
    'lag.annuller':   'Annullér',
    'lag.snartTom':   'Snart tom',
    'lag.tilføjUdløb':'+ Udløbsdato',
    'lag.udløbet':    'Udløbet',
    'lag.udløberIDag':'Udløber i dag',
    'lag.udløberIm':  'Udløber i morgen',
    'lag.omDage':     'om',
    'lag.dage':       'dage',
    'lag.vare':       'vare',
    'lag.varer':      'varer',
    'lag.udløberSnart':'udløber snart.',
    'lag.seRetter':   'Se retter der bruger dem →',
    'lag.kat.køl':       'Køl',
    'lag.kat.grønt':     'Grønt & Frugt',
    'lag.kat.tørvarer':  'Tørvarer & Konserves',
    'lag.kat.frys':      'Frys',
    'lag.kat.krydderier':'Krydderier',
    'lag.tilføjDialog.titel':  'Tilføj vare',
    'lag.tilføjDialog.navn':   'Varenavn',
    'lag.tilføjDialog.navnPh': 'fx Kyllingebryst',
    'lag.tilføjDialog.gem':    'Tilføj til lager',
    'lag.redigerDialog.titel': 'Rediger vare',
    'lag.redigerDialog.gem':   'Gem ændringer',

    // Profil
    'pf.redigerProfil':   'Rediger profil',
    'pf.retter':          'retter',
    'pf.følgere':         'følgere',
    'pf.følger':          'følger',
    'pf.mineTags':        'Mine tags',
    'pf.rediger':         'Rediger',
    'pf.tagsHint':        'Bruges til at skræddersy Mad-match og forslag',
    'pf.tilføjTags':      '+ Tilføj dine første tags',
    'pf.madvenner':       'Madvenner',
    'pf.tilføj':          '+ Tilføj',
    'pf.inviterTekst':    'Invitér dine venner til Brynjas Køkken og del madoplevelser!',
    'pf.tilføjFørste':    '+ Tilføj din første ven',
    'pf.statistik':       'Din madstatistik',
    'pf.streak':          '🔥 Dages streak',
    'pf.retterLavet':     '🍽️ Retter lavet',
    'pf.gnsTid':          '⏱ Gns. tid',
    'pf.likes':           'Likes',
    'pf.kreationer':      'Kreationer',
    'pf.badges':          'Badges',
    'pf.indstillinger':   'Indstillinger',
    'pf.notif':           'Notifikationer',
    'pf.notifSub':        'Daglige forslag kl. 17:00',
    'pf.sprog':           'Sprog',
    'pf.sprogsub':        'Dansk',
    'pf.privatliv':       'Privatliv',
    'pf.privatlivSub':    'Offentlig profil',
    'pf.hjælp':           'Hjælp & feedback',
    'pf.logUd':           'Log ud',
    'pf.logUdTitel':      'Log ud?',
    'pf.logUdTekst':      'Du kan altid logge ind igen med din e-mail og adgangskode.',
    'pf.logUdBekræft':    'Log ud',
    'pf.annuller':        'Annullér',
    'pf.swipeTip':        'Swipe højre i Mad-match for at gemme retter her.',
    'pf.åbnMadMatch':     'Åbn Mad-match',
    'pf.tagBillede':      'Tag et billede og skab din første kreation.',
    'pf.gåTilOpret':      'Gå til Opret',
    // Rediger profil
    'pf.re.titel':        'Rediger profil',
    'pf.re.email':        'E-mail',
    'pf.re.fornavn':      'Fornavn',
    'pf.re.efternavn':    'Efternavn',
    'pf.re.brugernavn':   'Brugernavn',
    'pf.re.telefon':      'Telefonnummer',
    'pf.re.bio':          'Bio',
    'pf.re.bioPh':        'Fortæl lidt om din madstil…',
    'pf.re.billede':      'Profilbillede',
    'pf.re.ellerEmoji':   'Eller vælg emoji-avatar',
    'pf.re.gem':          'Gem ændringer',
    'pf.re.gemmer':       'Gemmer…',
    'pf.re.annuller':     'Annullér',
    'pf.re.usernavnFejl': 'Brugernavn skal være mindst 3 tegn.',
    'pf.re.uploadFoto':   '🖼️ Upload foto',
    'pf.re.tagFoto':      '📷 Tag foto',
    // Sprog
    'pf.sp.titel':        'Sprog',
    'pf.sp.vælg':         'Vælg dit foretrukne sprog.',
    'pf.sp.dansk':        'Dansk',
    'pf.sp.english':      'English',
    // Notifikationer
    'pf.no.titel':        'Notifikationer',
    'pf.no.beskrivelse':  'Vælg hvornår Brynjas Køkken må sende dig beskeder.',
    'pf.no.daglige':      'Daglige madforslag',
    'pf.no.dagligeSub':   'Kl. 17:00 hver dag',
    'pf.no.venner':       'Venners aktivitet',
    'pf.no.vennerSub':    'Når nogen i dit netværk laver noget',
    'pf.no.ugentlig':     'Ugentlig madplan',
    'pf.no.ugentligSub':  'Mandag morgen',
    // Privatliv
    'pf.pv.titel':        'Privatliv',
    'pf.pv.beskrivelse':  'Styr hvad andre kan se om dig.',
    'pf.pv.offentlig':    'Offentlig profil',
    'pf.pv.offentligSub': 'Alle kan finde og se din profil',
    'pf.pv.aktivitet':    'Del aktivitet med venner',
    'pf.pv.aktivitetSub': 'Venner kan se hvad du laver',
    'pf.pv.streak':       'Vis streak offentligt',
    'pf.pv.streakSub':    'Din streak vises på din profil',
    // Hjælp
    'pf.hj.titel':        'Hjælp & feedback',
    'pf.hj.faqTitel':     'Ofte stillede spørgsmål',
    'pf.hj.feedbackTitel':'Send feedback',
    'pf.hj.feedbackPh':   'Fortæl os hvad du synes…',
    'pf.hj.send':         'Send',
    'pf.hj.tak':          '✅ Tak for din feedback!',
    'pf.hj.version':      'Brynjas Køkken · Version 0.1.0',
    'pf.hj.faq0q':        'Hvordan tilføjer jeg råvarer til mit lager?',
    'pf.hj.faq0a':        'Gå til "Lager" og tryk "+ Tilføj".',
    'pf.hj.faq1q':        'Hvordan virker Mad-match?',
    'pf.hj.faq1a':        'Swipe til højre for at gemme, til venstre for at springe over. Aktiver "Matcher mit lager" for retter du kan lave nu.',
    'pf.hj.faq2q':        'Hvad gør Opret-funktionen?',
    'pf.hj.faq2a':        'Tag et billede af dine råvarer og lad AI finde en opskrift til dig.',
    'pf.hj.faq3q':        'Kan jeg bruge appen offline?',
    'pf.hj.faq3a':        'Ja, dine data gemmes lokalt på enheden.',
    // Tilføj ven
    'pf.tv.titel':        'Find en ven',
    'pf.tv.tekst':        'Søg på brugernavn for at følge nogen.',
    'pf.tv.følg':         'Følg',
    'pf.tv.tilføjer':     'Tilføjer…',
    'pf.tv.annuller':     'Annullér',
    // Tags side
    'pf.ts.titel':        'Mine tags',
    'pf.ts.beskrivelse':  'Vælg tags der passer til dig — de bruges til at skræddersy Mad-match og dine daglige forslag.',
    'pf.ts.gemTags':      'Gem tags',
    'pf.ts.valgt':        'valgt',
    'pf.ts.annuller':     'Annullér',

    // Login
    'li.velkomst':       'Velkommen tilbage',
    'li.undertitel':     'Log ind på din konto',
    'li.email':          'E-mail',
    'li.adgangskode':    'Adgangskode',
    'li.glemt':          'Glemt adgangskode?',
    'li.logInd':         'Log ind',
    'li.loggerInd':      'Logger ind…',
    'li.ingenKonto':     'Ingen konto?',
    'li.opretHer':       'Opret dig her',
    'li.glemtTitel':     'Glemt adgangskode?',
    'li.glemtTekst':     'Indtast din e-mail, så sender vi et nulstillingslink.',
    'li.sendLink':       'Send nulstillingslink',
    'li.sender':         'Sender…',
    'li.tjekMail':       'Tjek din mail',
    'li.mailSendt1':     'Har vi en konto med',
    'li.mailSendt2':     ', sender vi et nulstillingslink om lidt.',
    'li.tilbageLogin':   'Tilbage til login',
    'li.nyAdg':          'Ny adgangskode',
    'li.nyAdgPh':        'Min. 6 tegn',
    'li.gentagAdg':      'Gentag adgangskode',
    'li.gentagPh':       'Samme adgangskode',
    'li.gemNy':          'Gem ny adgangskode',
    'li.tilbage':        '‹ Tilbage',

    // Register
    'reg.brand':         'Brynjas Køkken',
    'reg.trin':          'Trin',
    'reg.af':            'af',
    'reg.opret':         'Opret din konto',
    'reg.underT':        'Fortæl os lidt om dig, så vi kan personalisere Brynjas Køkken.',
    'reg.fornavn':       'Fornavn',
    'reg.efternavn':     'Efternavn',
    'reg.email':         'E-mail',
    'reg.brugernavn':    'Brugernavn',
    'reg.telefon':       'Telefon (valgfrit)',
    'reg.næste':         'Næste trin',
    'reg.adgangskode':   'Adgangskode',
    'reg.gentag':        'Gentag adgangskode',
    'reg.opretKnap':     'Opret konto',
    'reg.opretter':      'Opretter…',
    'reg.harKonto':      'Har du allerede en konto?',
    'reg.logIndHer':     'Log ind her',
    'reg.tilbage':       '‹ Tilbage',
    'reg.fejlAllefelter':'Alle felter undtagen telefon skal udfyldes.',
    'reg.fejlEmail':     'Indtast en gyldig e-mailadresse.',
    'reg.fejlBrugernavn':'Brugernavn skal være mindst 3 tegn.',
    'reg.fejlMatch':     'Adgangskoderne matcher ikke.',
    'reg.adgPh':         'Min. 6 tegn',
    'reg.gentagPh':      'Samme adgangskode',

    // Indkøbsliste
    'il.titel':          'Indkøbsliste',
    'il.tom':            'Din indkøbsliste er tom',
    'il.tomSub':         'Åbn en opskrift og tilføj de manglende ingredienser direkte.',
    'il.tilføjManuelt':  '+ Tilføj manuelt',
    'il.rydTjekkede':    'Ryd tjekkede',
    'il.flytTilLager':   'Flyt til lager',
    'il.flyttes':        'Flytter…',
    'il.fraOpskrift':    'Fra:',
    'il.vareNavnPh':     'Varenavn…',
    'il.tilføj':         'Tilføj',
    'il.annuller':       'Annullér',
    'il.flytToast':      'varer tilføjet til dit lager!',
    'il.flytToastEn':    'vare tilføjet til dit lager!',

    // Notifikationer
    'notif.titel':   'Notifikationer',
    'notif.tom':     'Ingen notifikationer endnu',
    'notif.tomSub':  'Når nogen følger dig eller liker dine kreationer, ser du det her.',
    'notif.følger':  'begyndte at følge dig',
    'notif.likede':  'likede din kreation',
    'notif.henter':  'Henter…',

    // Bruger profil
    'bp.kreationer':     'kreationer',
    'bp.kreation':       'kreation',
    'bp.kreationerTitel':'Kreationer',
    'bp.tom':            'Ingen kreationer endnu',
    'bp.lavOgså':        'Lav også →',
    'bp.ikkeFundet':     'Bruger ikke fundet',
    'bp.tilbage':        '← Tilbage',
  },

  en: {
    // Nav
    'nav.hjem':     'Home',
    'nav.madmatch': 'Food Match',
    'nav.opret':    'Create',
    'nav.lager':    'Pantry',
    'nav.profil':   'Profile',

    // Relative time
    'tid.ligeNu':   'Just now',
    'tid.minSiden': 'min ago',
    'tid.tSiden':   'h ago',
    'tid.dagSiden': 'day ago',
    'tid.dageSiden':'days ago',
    'tid.timeEnhed':'h',

    // Difficulty
    'sværhed.1': 'Easy',
    'sværhed.2': 'Medium',
    'sværhed.3': 'Hard',

    // Hjem
    'hjem.godmorgen':       'Good morning',
    'hjem.godFormiddag':    'Good morning',
    'hjem.godEftermiddag':  'Good afternoon',
    'hjem.godAftenen':      'Good evening',
    'hjem.klar':            'Ready to cook?',
    'hjem.aktivNu':         'Active now',
    'hjem.ingenAktive':     'No friends active',
    'hjem.søgPlaceholder':  '🔍 Search recipes…',
    'hjem.søgIngen':        'No results for',
    'hjem.streakLabel':     'day streak!',
    'hjem.senesteFeed':     'Recent dishes in your network',
    'hjem.ingenFeed':       'Nothing to show yet',
    'hjem.ingenFeedSub':    'Add friends and cook to see activity here.',
    'hjem.likerDu':         'liked',
    'hjem.kokkehat':        '🧑‍🍳',

    // Mad-match / Food Match
    'mm.kunKanLaves': '✓ Only what I can make now',
    'mm.titel':       'Food Match',
    'mm.subtitle':    'Swipe your way to dinner',
    'mm.mitLager':    '🧺 My pantry',
    'mm.under30':     '⏱ Under 30 min',
    'mm.vegetar':     'Vegetarian',
    'mm.kød':         'Meat',
    'mm.fisk':        'Fish',
    'mm.morgen':      '🌅 Breakfast',
    'mm.frokost':     '🥗 Lunch',
    'mm.aftensmad':   '🍽️ Dinner',
    'mm.henter':      'Loading recipes…',
    'mm.tomTitel':    "That's all!",
    'mm.tomGemte':    'You saved',
    'mm.tomRet':      'dish',
    'mm.tomRetter':   'dishes',
    'mm.tomForfra':   'Start over',

    // Opskrift / Recipe
    'op.henter':          'Loading recipe…',
    'op.ikkeFundet':      'Recipe not found',
    'op.tilbage':         '← Back',
    'op.ingredienser':    'Ingredients',
    'op.fremgangsmåde':   'Instructions',
    'op.mineNoter':       'My notes',
    'op.duHarAlt':        'You have everything ✓',
    'op.mangler':         'missing',
    'op.tilpasMængde':    'Adjust serving',
    'op.pers':            'serv.',
    'op.stk':             'pcs',
    'op.nulstilTil':      'Reset to',
    'op.fra':             'from',
    'op.noterPh':         'Write your own notes, adaptations or tips here…',
    'op.seOriginal':      'See original recipe at',
    'op.tilføjIndkøb':    '🛒 Add missing to shopping list',
    'op.tilføjAlt':       '🛒 Add all to shopping list',
    'op.tilføjtBekræft':  'added to your shopping list!',
    'op.startKnap':       '🍳 Start cooking',
    'op.chatSpørg':       'Ask about the recipe',
    'op.chatPh':          'Ask a question…',
    'op.chatVelkomst':    "Hi! I know this recipe inside out — what would you like to know?",
    'op.chatFejl':        'Sorry, something went wrong. Please try again.',
    'op.chatOffTopic':    "I'm only an expert on this dish! Ask me about ingredients, cooking tips, substitutions or serving suggestions 😊",
    'op.chatLang':        'Always respond in English.',

    // Kok / Cook mode
    'kok.henter':        'Loading recipe…',
    'kok.ikkeFundet':    'Recipe not found',
    'kok.pause':         '⏸ Pause',
    'kok.start':         '▶ Start',
    'kok.nulstil':       '⏹ Reset',
    'kok.ingredienser':  'Ingredients',
    'kok.trin':          'Step',
    'kok.af':            'of',
    'kok.afslut':        '✓ Finish',
    'kok.modal.titel':   'How did it go?',
    'kok.modal.brugte':  'You spent',
    'kok.modal.på':      'on',
    'kok.modal.tagFoto': 'Take photo',
    'kok.modal.upload':  'Upload photo',
    'kok.modal.del':     'Share with community 🌍',
    'kok.modal.citatPh': 'Add a comment… (optional)',
    'kok.modal.fortsæt': 'Continue',
    'kok.modal.gemDel':  'Save & Share',
    'kok.modal.arkiv':   'Save to archive',
    'kok.modal.gemmer':  'Saving…',
    'kok.modal.fejl':    "Photo couldn't be uploaded — please try again.",
    'kok.færdig.titel':  'Well done! 🎉',
    'kok.færdig.tekst':  'Your creation has been saved.',
    'kok.færdig.tilbage':'Back to recipe',

    // Lager / Pantry
    'lag.titel':      'Pantry',
    'lag.tilføj':     '+ Add',
    'lag.tom':        'Your pantry is empty',
    'lag.tomSub':     'Add ingredients to see which recipes you can make.',
    'lag.søgPh':      'Search or type a name…',
    'lag.mængde':     'Quantity',
    'lag.enhed':      'Unit',
    'lag.udløber':    'Expires',
    'lag.slet':       'Delete',
    'lag.gem':        'Save',
    'lag.annuller':   'Cancel',
    'lag.snartTom':   'Running low',
    'lag.tilføjUdløb':'+ Expiry date',
    'lag.udløbet':    'Expired',
    'lag.udløberIDag':'Expires today',
    'lag.udløberIm':  'Expires tomorrow',
    'lag.omDage':     'in',
    'lag.dage':       'days',
    'lag.vare':       'item',
    'lag.varer':      'items',
    'lag.udløberSnart':'expiring soon.',
    'lag.seRetter':   'See recipes that use them →',
    'lag.kat.køl':       'Refrigerated',
    'lag.kat.grønt':     'Produce',
    'lag.kat.tørvarer':  'Dry Goods',
    'lag.kat.frys':      'Frozen',
    'lag.kat.krydderier':'Spices',
    'lag.tilføjDialog.titel':  'Add item',
    'lag.tilføjDialog.navn':   'Item name',
    'lag.tilføjDialog.navnPh': 'e.g. Chicken breast',
    'lag.tilføjDialog.gem':    'Add to pantry',
    'lag.redigerDialog.titel': 'Edit item',
    'lag.redigerDialog.gem':   'Save changes',

    // Profil / Profile
    'pf.redigerProfil':   'Edit profile',
    'pf.retter':          'dishes',
    'pf.følgere':         'followers',
    'pf.følger':          'following',
    'pf.mineTags':        'My tags',
    'pf.rediger':         'Edit',
    'pf.tagsHint':        'Used to personalise Food Match and suggestions',
    'pf.tilføjTags':      '+ Add your first tags',
    'pf.madvenner':       'Food friends',
    'pf.tilføj':          '+ Add',
    'pf.inviterTekst':    'Invite your friends to Brynjas Køkken and share food experiences!',
    'pf.tilføjFørste':    '+ Add your first friend',
    'pf.statistik':       'Your food stats',
    'pf.streak':          '🔥 Day streak',
    'pf.retterLavet':     '🍽️ Dishes cooked',
    'pf.gnsTid':          '⏱ Avg. time',
    'pf.likes':           'Likes',
    'pf.kreationer':      'Creations',
    'pf.badges':          'Badges',
    'pf.indstillinger':   'Settings',
    'pf.notif':           'Notifications',
    'pf.notifSub':        'Daily suggestions at 5 PM',
    'pf.sprog':           'Language',
    'pf.sprogsub':        'English',
    'pf.privatliv':       'Privacy',
    'pf.privatlivSub':    'Public profile',
    'pf.hjælp':           'Help & feedback',
    'pf.logUd':           'Log out',
    'pf.logUdTitel':      'Log out?',
    'pf.logUdTekst':      'You can always log back in with your email and password.',
    'pf.logUdBekræft':    'Log out',
    'pf.annuller':        'Cancel',
    'pf.swipeTip':        'Swipe right in Food Match to save dishes here.',
    'pf.åbnMadMatch':     'Open Food Match',
    'pf.tagBillede':      'Take a photo and create your first dish.',
    'pf.gåTilOpret':      'Go to Create',
    // Edit profile
    'pf.re.titel':        'Edit profile',
    'pf.re.email':        'Email',
    'pf.re.fornavn':      'First name',
    'pf.re.efternavn':    'Last name',
    'pf.re.brugernavn':   'Username',
    'pf.re.telefon':      'Phone number',
    'pf.re.bio':          'Bio',
    'pf.re.bioPh':        'Tell us about your cooking style…',
    'pf.re.billede':      'Profile photo',
    'pf.re.ellerEmoji':   'Or choose an emoji avatar',
    'pf.re.gem':          'Save changes',
    'pf.re.gemmer':       'Saving…',
    'pf.re.annuller':     'Cancel',
    'pf.re.usernavnFejl': 'Username must be at least 3 characters.',
    'pf.re.uploadFoto':   '🖼️ Upload photo',
    'pf.re.tagFoto':      '📷 Take photo',
    // Language
    'pf.sp.titel':        'Language',
    'pf.sp.vælg':         'Choose your preferred language.',
    'pf.sp.dansk':        'Dansk',
    'pf.sp.english':      'English',
    // Notifications
    'pf.no.titel':        'Notifications',
    'pf.no.beskrivelse':  'Choose when Brynjas Køkken can send you messages.',
    'pf.no.daglige':      'Daily food suggestions',
    'pf.no.dagligeSub':   'At 5 PM every day',
    'pf.no.venner':       "Friends' activity",
    'pf.no.vennerSub':    'When someone in your network cooks something',
    'pf.no.ugentlig':     'Weekly meal plan',
    'pf.no.ugentligSub':  'Monday morning',
    // Privacy
    'pf.pv.titel':        'Privacy',
    'pf.pv.beskrivelse':  'Control what others can see about you.',
    'pf.pv.offentlig':    'Public profile',
    'pf.pv.offentligSub': 'Anyone can find and view your profile',
    'pf.pv.aktivitet':    'Share activity with friends',
    'pf.pv.aktivitetSub': 'Friends can see what you cook',
    'pf.pv.streak':       'Show streak publicly',
    'pf.pv.streakSub':    'Your streak is shown on your profile',
    // Help
    'pf.hj.titel':        'Help & feedback',
    'pf.hj.faqTitel':     'Frequently asked questions',
    'pf.hj.feedbackTitel':'Send feedback',
    'pf.hj.feedbackPh':   'Tell us what you think…',
    'pf.hj.send':         'Send',
    'pf.hj.tak':          '✅ Thank you for your feedback!',
    'pf.hj.version':      'Brynjas Køkken · Version 0.1.0',
    'pf.hj.faq0q':        'How do I add ingredients to my pantry?',
    'pf.hj.faq0a':        'Go to "Pantry" and tap "+ Add".',
    'pf.hj.faq1q':        'How does Food Match work?',
    'pf.hj.faq1a':        'Swipe right to save, left to skip. Enable "My pantry" to see dishes you can make right now.',
    'pf.hj.faq2q':        'What does the Create feature do?',
    'pf.hj.faq2a':        'Take a photo of your ingredients and let AI find a recipe for you.',
    'pf.hj.faq3q':        'Can I use the app offline?',
    'pf.hj.faq3a':        'Yes, your data is stored locally on your device.',
    // Add friend
    'pf.tv.titel':        'Find a friend',
    'pf.tv.tekst':        'Search by username to follow someone.',
    'pf.tv.følg':         'Follow',
    'pf.tv.tilføjer':     'Adding…',
    'pf.tv.annuller':     'Cancel',
    // Tags
    'pf.ts.titel':        'My tags',
    'pf.ts.beskrivelse':  'Choose tags that suit you — they are used to personalise Food Match and your daily suggestions.',
    'pf.ts.gemTags':      'Save tags',
    'pf.ts.valgt':        'selected',
    'pf.ts.annuller':     'Cancel',

    // Login
    'li.velkomst':       'Welcome back',
    'li.undertitel':     'Sign in to your account',
    'li.email':          'Email',
    'li.adgangskode':    'Password',
    'li.glemt':          'Forgot password?',
    'li.logInd':         'Sign in',
    'li.loggerInd':      'Signing in…',
    'li.ingenKonto':     'No account?',
    'li.opretHer':       'Create one here',
    'li.glemtTitel':     'Forgot your password?',
    'li.glemtTekst':     "Enter your email and we'll send you a reset link.",
    'li.sendLink':       'Send reset link',
    'li.sender':         'Sending…',
    'li.tjekMail':       'Check your email',
    'li.mailSendt1':     'If we have an account with',
    'li.mailSendt2':     ", we'll send a reset link shortly.",
    'li.tilbageLogin':   'Back to login',
    'li.nyAdg':          'New password',
    'li.nyAdgPh':        'Min. 6 characters',
    'li.gentagAdg':      'Repeat password',
    'li.gentagPh':       'Same password',
    'li.gemNy':          'Save new password',
    'li.tilbage':        '‹ Back',

    // Register
    'reg.brand':         'Brynjas Køkken',
    'reg.trin':          'Step',
    'reg.af':            'of',
    'reg.opret':         'Create your account',
    'reg.underT':        'Tell us a little about you so we can personalise Brynjas Køkken.',
    'reg.fornavn':       'First name',
    'reg.efternavn':     'Last name',
    'reg.email':         'Email',
    'reg.brugernavn':    'Username',
    'reg.telefon':       'Phone (optional)',
    'reg.næste':         'Next step',
    'reg.adgangskode':   'Password',
    'reg.gentag':        'Repeat password',
    'reg.opretKnap':     'Create account',
    'reg.opretter':      'Creating…',
    'reg.harKonto':      'Already have an account?',
    'reg.logIndHer':     'Sign in here',
    'reg.tilbage':       '‹ Back',
    'reg.fejlAllefelter':'All fields except phone must be filled in.',
    'reg.fejlEmail':     'Please enter a valid email address.',
    'reg.fejlBrugernavn':'Username must be at least 3 characters.',
    'reg.fejlMatch':     "Passwords don't match.",
    'reg.adgPh':         'Min. 6 characters',
    'reg.gentagPh':      'Same password',

    // Shopping list
    'il.titel':          'Shopping list',
    'il.tom':            'Your shopping list is empty',
    'il.tomSub':         'Open a recipe and add the missing ingredients directly.',
    'il.tilføjManuelt':  '+ Add manually',
    'il.rydTjekkede':    'Clear checked',
    'il.flytTilLager':   'Move to pantry',
    'il.flyttes':        'Moving…',
    'il.fraOpskrift':    'From:',
    'il.vareNavnPh':     'Item name…',
    'il.tilføj':         'Add',
    'il.annuller':       'Cancel',
    'il.flytToast':      'items added to your pantry!',
    'il.flytToastEn':    'item added to your pantry!',

    // Notifications
    'notif.titel':   'Notifications',
    'notif.tom':     'No notifications yet',
    'notif.tomSub':  "When someone follows you or likes your creations, you'll see it here.",
    'notif.følger':  'started following you',
    'notif.likede':  'liked your creation',
    'notif.henter':  'Loading…',

    // Bruger profil / User profile
    'bp.kreationer':     'creations',
    'bp.kreation':       'creation',
    'bp.kreationerTitel':'Creations',
    'bp.tom':            'No creations yet',
    'bp.lavOgså':        'Make it too →',
    'bp.ikkeFundet':     'User not found',
    'bp.tilbage':        '← Back',
  },
}

// ── Context ───────────────────────────────────────────────────────────────────

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem(LANG_KEY) ?? 'da')

  const setLang = useCallback((code) => {
    localStorage.setItem(LANG_KEY, code)
    setLangState(code)
  }, [])

  const t = useCallback(
    (key) => T[lang]?.[key] ?? T['da']?.[key] ?? key,
    [lang]
  )

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used inside LangProvider')
  return ctx
}

// ── Helpers that need lang ────────────────────────────────────────────────────

export function relativTidLang(isoString, t) {
  const diff = Date.now() - new Date(isoString).getTime()
  const min = Math.floor(diff / 60000)
  if (min < 1) return t('tid.ligeNu')
  if (min < 60) return `${min} ${t('tid.minSiden')}`
  const timer = Math.floor(min / 60)
  if (timer < 24) return `${timer} ${t('tid.tSiden')}`
  const dage = Math.floor(timer / 24)
  return `${dage} ${dage > 1 ? t('tid.dageSiden') : t('tid.dagSiden')}`
}

export function datoLinjeLang(lang) {
  const locale = lang === 'en' ? 'en-GB' : 'da-DK'
  return new Date()
    .toLocaleDateString(locale, { weekday: 'long', day: 'numeric', month: 'long' })
    .toUpperCase()
}
